/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;



import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import myapp.*;
/**
 *
 * @author Sam
 */
public class settingsPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form settingsPage
     */
    public settingsPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null); 
    }
Color navcolor = new Color(102,102,102);
    Color headcolor = new Color(0,255,255);
    Color bodycolor = new Color(255, 153, 153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        manager = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconsfolder/samsam2.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 210, 140));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(390, 40, 190, 140);

        jLabel1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel1.setText("Account Settings");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 440, 40);

        jLabel2.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel2.setText("Address: Vito Minglanilla Cebu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 300, 30);

        jLabel10.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel10.setText("Account Name: Cosam John A. Macua");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 50, 360, 30);

        jLabel12.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel12.setText("Position: Administrator");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 80, 300, 40);

        jLabel13.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel13.setText("Email: sammacua23@gmailcom");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 120, 300, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 242));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        logout.setBackground(new java.awt.Color(0, 255, 255));
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.setForeground(new java.awt.Color(204, 204, 204));
        logout.setPreferredSize(new java.awt.Dimension(170, 170));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconsfolder/icons8-logout-rounded-100.png"))); // NOI18N
        logout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 90));

        jLabel4.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel4.setText("Logout");
        logout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        jPanel2.add(logout);
        logout.setBounds(400, 40, 140, 150);

        manager.setBackground(new java.awt.Color(0, 255, 255));
        manager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manager.setPreferredSize(new java.awt.Dimension(170, 170));
        manager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managerMouseExited(evt);
            }
        });
        manager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconsfolder/icons8-admin-settings-male-100.png"))); // NOI18N
        manager.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, -1));

        jLabel6.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel6.setText("Manage User");
        manager.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        jPanel2.add(manager);
        manager.setBounds(20, 40, 160, 150);

        reports.setBackground(new java.awt.Color(0, 255, 255));
        reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reports.setPreferredSize(new java.awt.Dimension(170, 170));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconsfolder/icons8-reports-100.png"))); // NOI18N
        reports.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, -1));

        jLabel8.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        jLabel8.setText("Reports ");
        reports.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, -1));

        jPanel2.add(reports);
        reports.setBounds(210, 40, 150, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconsfolder/result.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(-50, -210, 610, 770);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
             
    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(navcolor);       
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         logout.setBackground(headcolor);
    }//GEN-LAST:event_logoutMouseExited

    private void managerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerMouseEntered
        manager.setBackground(navcolor);
    }//GEN-LAST:event_managerMouseEntered

    private void managerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerMouseExited
       manager.setBackground(headcolor);
    }//GEN-LAST:event_managerMouseExited

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        reports.setBackground(navcolor);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
       reports.setBackground(headcolor);
    }//GEN-LAST:event_reportsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
      JFrame mainFrame = (JFrame)SwingUtilities.getWindowAncestor(this);
      mainFrame.dispose();
     loginForm If = new loginForm();
     If.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel manager;
    private javax.swing.JPanel reports;
    // End of variables declaration//GEN-END:variables
}
